import Link from "next/link"
import { PageShell } from "@/components/page-shell"
import { Button } from "@/components/ui/button"

const dimensions = ["Market fit", "Offer value", "Lead activity", "Funnel gap", "Operational maturity", "Sales ownership", "Implementation readiness"]

export default function Fit7Page() {
  return <PageShell><section className="relative overflow-hidden py-20 sm:py-28"><div className="pointer-events-none absolute left-1/2 top-20 h-72 w-72 -translate-x-1/2 rounded-full bg-primary/5 blur-3xl" /><div className="relative mx-auto max-w-5xl px-4 sm:px-6"><p className="font-mono text-sm uppercase tracking-[.2em] text-primary">FIT-7™ Assessment</p><h1 className="mt-4 text-4xl font-bold sm:text-6xl">Find the constraint before building the funnel.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">FIT-7™ is NorthForge’s preliminary framework for examining seven conditions that influence whether a lead and booking system is ready to be built, repaired or nurtured first.</p><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{dimensions.map((item, index) => <div key={item} className="group relative overflow-hidden rounded-xl border border-border bg-card p-5 transition-all duration-300 ease-out hover:-translate-y-2 hover:border-primary/70 hover:bg-primary/[.07] hover:shadow-[0_20px_55px_rgba(20,184,166,.16)] motion-reduce:transform-none"><div className="pointer-events-none absolute -right-12 -top-12 h-28 w-28 rounded-full bg-primary/0 blur-2xl transition-all duration-500 group-hover:bg-primary/20" /><span className="relative inline-flex h-9 min-w-9 items-center justify-center rounded-full border border-primary/25 bg-primary/5 px-2 font-mono text-sm text-primary transition-all duration-300 group-hover:scale-110 group-hover:border-primary/70 group-hover:bg-primary group-hover:text-primary-foreground">0{index + 1}</span><h2 className="relative mt-4 font-semibold transition-colors duration-300 group-hover:text-primary">{item}</h2></div>)}</div><div className="mt-12 rounded-2xl border border-border bg-muted/30 p-7 transition-all duration-300 hover:border-primary/50 hover:shadow-[0_18px_50px_rgba(20,184,166,.1)]"><h2 className="text-xl font-semibold">Assessment launch status</h2><p className="mt-3 text-muted-foreground">The public scoring form will activate only after its privacy contact, secure data destination and retention procedure are connected and tested. No personal assessment data is being collected on this page yet.</p><Button asChild className="group mt-6 hover:-translate-y-1 hover:shadow-[0_0_36px_rgba(20,184,166,.25)]"><Link href="/start-project?service=lead-booking-funnel-systems">Request a manual funnel review <span aria-hidden="true" className="transition-transform duration-300 group-hover:translate-x-1">→</span></Link></Button></div></div></section></PageShell>
}
